// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1YCmynB2SbXNZD-GdxZdLCYeC9vVL1Eo',
    appId: '1:545995255567:web:1bea1cd0efb62a7203d87a',
    messagingSenderId: '545995255567',
    projectId: 'attendance-pulse',
    authDomain: 'attendance-pulse.firebaseapp.com',
    storageBucket: 'attendance-pulse.firebasestorage.app',
    measurementId: 'G-N776VEJDZ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvna4N07hpstSsuwxqh2zz379-Ks4LDMc',
    appId: '1:545995255567:android:62f401ad6e33f19c03d87a',
    messagingSenderId: '545995255567',
    projectId: 'attendance-pulse',
    storageBucket: 'attendance-pulse.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeVLqpY2uLS3wmzrw2tqMA7OPeaQkagws',
    appId: '1:545995255567:ios:45ebdcc0d222f16103d87a',
    messagingSenderId: '545995255567',
    projectId: 'attendance-pulse',
    storageBucket: 'attendance-pulse.firebasestorage.app',
    iosBundleId: 'com.example.attendancePulse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1YCmynB2SbXNZD-GdxZdLCYeC9vVL1Eo',
    appId: '1:545995255567:web:1bea1cd0efb62a7203d87a',
    messagingSenderId: '545995255567',
    projectId: 'attendance-pulse',
    authDomain: 'attendance-pulse.firebaseapp.com',
    storageBucket: 'attendance-pulse.firebasestorage.app',
    measurementId: 'G-N776VEJDZ1',
  );
}
